version: "3"

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      DSN: host=db user=postgres password=1234 dbname=jobguru port=5432 sslmode=disable
    command: go run ./cmd/main.go -b 0.0.0.0

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: jobguru
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./pg_hba.conf:/etc/postgresql/13/main/pg_hba.conf
    ports:
      - "5432:5432"
